variables:
    # Container registry service connection established during pipeline creation
    dockerRegistryServiceConnection: devops-acr-connection
    imageRepository: devops-course-repository
    containerRegistry: devopscourseregistry
    dockerfilePath: '$(System.DefaultWorkingDirectory)/_DevOpsCourse/devopswebapp/Dockerfile'
    tag: 'latest'

    # Agent VM image name
    vmImageName: 'ubuntu-latest'

steps:

- task: AzureWebAppContainer@1 # Description what the task will execute
  inputs:
    azureSubscription: 'devops-course-service-connection'
    appName: 'devops-course-webapp-test'
    containers: $(containerRegistry)/$(imageRepository):$(tag)